language: node_js
node_js:
  - '6'
addons:
  postgresql: '9.4'

#########################
## Setup
#########################
sudo: true
cache:
  directories:
    - node_modules
    - $HOME/.yarn-cache
services:
  - postgresql

#########################
## Install Yarn
##
## From https://yarnpkg.com/en/docs/install-ci#travis-tab
#########################
before_install:
  # Repo for Yarn
  - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn

install: yarn

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - npm prune

after_success:
  - npm run coverage
  - npm run semantic-release
  - npm run reparo

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

#########################
## Notifications
#########################
notifications:
  email: false
  slack:
    secure: XR/vJ53xf+IkDmE/cMj9p2C9w4DVRN7/0/NjRDxYpQD/spqGl9jBz9kkVWCAprKigVhLVCZnYELaFpNPO39GGuxwh44sIkCq8XtnKKtikLKMbTc8CFNKpla8Qf/nHiKts+wxycbEQOCL2apQIFaAEs1nWNpZqKdhemoDtPXLTKRZLxMm0494iDn50klrAnrieqJOMt0Q0/XfC5AfmIM3yZxeRhbq0Oq6IV1uT4IZSIOejaMLV6Y6nQKHaYHHklVrDc1OaBMJO/MiIiDzUt0kONkQREbsZf5tka30MhHyvT660GcgZv8E9EBN/STTZ5pO23cD3JJE72SUCYpcWjguIzDxd9kohi9QMHk2NOfO0G7B5b87lRxlMk3I4ce7z0Gg+ToQ2c5T83i/Zj6B/lbdVzwUlPU+nVopjA2oVsm2GnqLEAbg1a2IY34xtATxBgS2wS68ZRZFD3YnrPYRIJBeddqdEWw95R2OiVQNH2/hUBb4UYnjzynKdhHSiuBAGhgbyYZHjDs1sGpdQvAdpwoBdXSun9jDxRhb5FIg1JOqIBFFe8vjEg1RYqLDjm4VSBVOkUI9Uudpa3TIg8cfGVczr81RJ5yy6fGDoYUfzr9Zq7pim9kE22WLzw7k0XeyKVN/aRTlBZsgfvvIzIijJrSexhKrHJHB/jcMUlcdP9fgGFQ=
